!- mode(gt(+,+)).

gt(polar1,polar0).
gt(polar2,polar0).
gt(polar3,polar0).
gt(polar4,polar0).
gt(polar5,polar0).
gt(polar6,polar0).
gt(polar7,polar0).
gt(polar8,polar0).
gt(polar9,polar0).
gt(polar2,polar1).
gt(polar3,polar1).
gt(polar4,polar1).
gt(polar5,polar1).
gt(polar6,polar1).
gt(polar7,polar1).
gt(polar8,polar1).
gt(polar9,polar1).
gt(polar3,polar2).
gt(polar4,polar2).
gt(polar5,polar2).
gt(polar6,polar2).
gt(polar7,polar2).
gt(polar8,polar2).
gt(polar9,polar2).
gt(polar4,polar3).
gt(polar5,polar3).
gt(polar6,polar3).
gt(polar7,polar3).
gt(polar8,polar3).
gt(polar9,polar3).
gt(polar5,polar4).
gt(polar6,polar4).
gt(polar7,polar4).
gt(polar8,polar4).
gt(polar9,polar4).
gt(polar6,polar5).
gt(polar7,polar5).
gt(polar8,polar5).
gt(polar9,polar5).
gt(polar7,polar6).
gt(polar8,polar6).
gt(polar9,polar6).
gt(polar8,polar7).
gt(polar9,polar7).
gt(polar9,polar8).


gt(size1,size0).
gt(size2,size0).
gt(size3,size0).
gt(size4,size0).
gt(size5,size0).
gt(size6,size0).
gt(size7,size0).
gt(size8,size0).
gt(size9,size0).
gt(size2,size1).
gt(size3,size1).
gt(size4,size1).
gt(size5,size1).
gt(size6,size1).
gt(size7,size1).
gt(size8,size1).
gt(size9,size1).
gt(size3,size2).
gt(size4,size2).
gt(size5,size2).
gt(size6,size2).
gt(size7,size2).
gt(size8,size2).
gt(size9,size2).
gt(size4,size3).
gt(size5,size3).
gt(size6,size3).
gt(size7,size3).
gt(size8,size3).
gt(size9,size3).
gt(size5,size4).
gt(size6,size4).
gt(size7,size4).
gt(size8,size4).
gt(size9,size4).
gt(size6,size5).
gt(size7,size5).
gt(size8,size5).
gt(size9,size5).
gt(size7,size6).
gt(size8,size6).
gt(size9,size6).
gt(size8,size7).
gt(size9,size7).
gt(size9,size8).

gt(flex1,flex0).
gt(flex2,flex0).
gt(flex3,flex0).
gt(flex4,flex0).
gt(flex5,flex0).
gt(flex6,flex0).
gt(flex7,flex0).
gt(flex8,flex0).
gt(flex9,flex0).
gt(flex2,flex1).
gt(flex3,flex1).
gt(flex4,flex1).
gt(flex5,flex1).
gt(flex6,flex1).
gt(flex7,flex1).
gt(flex8,flex1).
gt(flex9,flex1).
gt(flex3,flex2).
gt(flex4,flex2).
gt(flex5,flex2).
gt(flex6,flex2).
gt(flex7,flex2).
gt(flex8,flex2).
gt(flex9,flex2).
gt(flex4,flex3).
gt(flex5,flex3).
gt(flex6,flex3).
gt(flex7,flex3).
gt(flex8,flex3).
gt(flex9,flex3).
gt(flex5,flex4).
gt(flex6,flex4).
gt(flex7,flex4).
gt(flex8,flex4).
gt(flex9,flex4).
gt(flex6,flex5).
gt(flex7,flex5).
gt(flex8,flex5).
gt(flex9,flex5).
gt(flex7,flex6).
gt(flex8,flex6).
gt(flex9,flex6).
gt(flex8,flex7).
gt(flex9,flex7).
gt(flex9,flex8).

gt(h_acceptor1,h_acceptor0).
gt(h_acceptor2,h_acceptor0).
gt(h_acceptor3,h_acceptor0).
gt(h_acceptor4,h_acceptor0).
gt(h_acceptor5,h_acceptor0).
gt(h_acceptor6,h_acceptor0).
gt(h_acceptor7,h_acceptor0).
gt(h_acceptor8,h_acceptor0).
gt(h_acceptor9,h_acceptor0).
gt(h_acceptor2,h_acceptor1).
gt(h_acceptor3,h_acceptor1).
gt(h_acceptor4,h_acceptor1).
gt(h_acceptor5,h_acceptor1).
gt(h_acceptor6,h_acceptor1).
gt(h_acceptor7,h_acceptor1).
gt(h_acceptor8,h_acceptor1).
gt(h_acceptor9,h_acceptor1).
gt(h_acceptor3,h_acceptor2).
gt(h_acceptor4,h_acceptor2).
gt(h_acceptor5,h_acceptor2).
gt(h_acceptor6,h_acceptor2).
gt(h_acceptor7,h_acceptor2).
gt(h_acceptor8,h_acceptor2).
gt(h_acceptor9,h_acceptor2).
gt(h_acceptor4,h_acceptor3).
gt(h_acceptor5,h_acceptor3).
gt(h_acceptor6,h_acceptor3).
gt(h_acceptor7,h_acceptor3).
gt(h_acceptor8,h_acceptor3).
gt(h_acceptor9,h_acceptor3).
gt(h_acceptor5,h_acceptor4).
gt(h_acceptor6,h_acceptor4).
gt(h_acceptor7,h_acceptor4).
gt(h_acceptor8,h_acceptor4).
gt(h_acceptor9,h_acceptor4).
gt(h_acceptor6,h_acceptor5).
gt(h_acceptor7,h_acceptor5).
gt(h_acceptor8,h_acceptor5).
gt(h_acceptor9,h_acceptor5).
gt(h_acceptor7,h_acceptor6).
gt(h_acceptor8,h_acceptor6).
gt(h_acceptor9,h_acceptor6).
gt(h_acceptor8,h_acceptor7).
gt(h_acceptor9,h_acceptor7).
gt(h_acceptor9,h_acceptor8).

gt(h_doner1,h_doner0).
gt(h_doner2,h_doner0).
gt(h_doner3,h_doner0).
gt(h_doner4,h_doner0).
gt(h_doner5,h_doner0).
gt(h_doner6,h_doner0).
gt(h_doner7,h_doner0).
gt(h_doner8,h_doner0).
gt(h_doner9,h_doner0).
gt(h_doner2,h_doner1).
gt(h_doner3,h_doner1).
gt(h_doner4,h_doner1).
gt(h_doner5,h_doner1).
gt(h_doner6,h_doner1).
gt(h_doner7,h_doner1).
gt(h_doner8,h_doner1).
gt(h_doner9,h_doner1).
gt(h_doner3,h_doner2).
gt(h_doner4,h_doner2).
gt(h_doner5,h_doner2).
gt(h_doner6,h_doner2).
gt(h_doner7,h_doner2).
gt(h_doner8,h_doner2).
gt(h_doner9,h_doner2).
gt(h_doner4,h_doner3).
gt(h_doner5,h_doner3).
gt(h_doner6,h_doner3).
gt(h_doner7,h_doner3).
gt(h_doner8,h_doner3).
gt(h_doner9,h_doner3).
gt(h_doner5,h_doner4).
gt(h_doner6,h_doner4).
gt(h_doner7,h_doner4).
gt(h_doner8,h_doner4).
gt(h_doner9,h_doner4).
gt(h_doner6,h_doner5).
gt(h_doner7,h_doner5).
gt(h_doner8,h_doner5).
gt(h_doner9,h_doner5).
gt(h_doner7,h_doner6).
gt(h_doner8,h_doner6).
gt(h_doner9,h_doner6).
gt(h_doner8,h_doner7).
gt(h_doner9,h_doner7).
gt(h_doner9,h_doner8).

gt(pi_doner1,pi_doner0).
gt(pi_doner2,pi_doner0).
gt(pi_doner3,pi_doner0).
gt(pi_doner4,pi_doner0).
gt(pi_doner5,pi_doner0).
gt(pi_doner6,pi_doner0).
gt(pi_doner7,pi_doner0).
gt(pi_doner8,pi_doner0).
gt(pi_doner9,pi_doner0).
gt(pi_doner2,pi_doner1).
gt(pi_doner3,pi_doner1).
gt(pi_doner4,pi_doner1).
gt(pi_doner5,pi_doner1).
gt(pi_doner6,pi_doner1).
gt(pi_doner7,pi_doner1).
gt(pi_doner8,pi_doner1).
gt(pi_doner9,pi_doner1).
gt(pi_doner3,pi_doner2).
gt(pi_doner4,pi_doner2).
gt(pi_doner5,pi_doner2).
gt(pi_doner6,pi_doner2).
gt(pi_doner7,pi_doner2).
gt(pi_doner8,pi_doner2).
gt(pi_doner9,pi_doner2).
gt(pi_doner4,pi_doner3).
gt(pi_doner5,pi_doner3).
gt(pi_doner6,pi_doner3).
gt(pi_doner7,pi_doner3).
gt(pi_doner8,pi_doner3).
gt(pi_doner9,pi_doner3).
gt(pi_doner5,pi_doner4).
gt(pi_doner6,pi_doner4).
gt(pi_doner7,pi_doner4).
gt(pi_doner8,pi_doner4).
gt(pi_doner9,pi_doner4).
gt(pi_doner6,pi_doner5).
gt(pi_doner7,pi_doner5).
gt(pi_doner8,pi_doner5).
gt(pi_doner9,pi_doner5).
gt(pi_doner7,pi_doner6).
gt(pi_doner8,pi_doner6).
gt(pi_doner9,pi_doner6).
gt(pi_doner8,pi_doner7).
gt(pi_doner9,pi_doner7).
gt(pi_doner9,pi_doner8).
gt(pi_acceptor1,pi_acceptor0).
gt(pi_acceptor2,pi_acceptor0).
gt(pi_acceptor3,pi_acceptor0).
gt(pi_acceptor4,pi_acceptor0).
gt(pi_acceptor5,pi_acceptor0).
gt(pi_acceptor6,pi_acceptor0).
gt(pi_acceptor7,pi_acceptor0).
gt(pi_acceptor8,pi_acceptor0).
gt(pi_acceptor9,pi_acceptor0).
gt(pi_acceptor2,pi_acceptor1).
gt(pi_acceptor3,pi_acceptor1).
gt(pi_acceptor4,pi_acceptor1).
gt(pi_acceptor5,pi_acceptor1).
gt(pi_acceptor6,pi_acceptor1).
gt(pi_acceptor7,pi_acceptor1).
gt(pi_acceptor8,pi_acceptor1).
gt(pi_acceptor9,pi_acceptor1).
gt(pi_acceptor3,pi_acceptor2).
gt(pi_acceptor4,pi_acceptor2).
gt(pi_acceptor5,pi_acceptor2).
gt(pi_acceptor6,pi_acceptor2).
gt(pi_acceptor7,pi_acceptor2).
gt(pi_acceptor8,pi_acceptor2).
gt(pi_acceptor9,pi_acceptor2).
gt(pi_acceptor4,pi_acceptor3).
gt(pi_acceptor5,pi_acceptor3).
gt(pi_acceptor6,pi_acceptor3).
gt(pi_acceptor7,pi_acceptor3).
gt(pi_acceptor8,pi_acceptor3).
gt(pi_acceptor9,pi_acceptor3).
gt(pi_acceptor5,pi_acceptor4).
gt(pi_acceptor6,pi_acceptor4).
gt(pi_acceptor7,pi_acceptor4).
gt(pi_acceptor8,pi_acceptor4).
gt(pi_acceptor9,pi_acceptor4).
gt(pi_acceptor6,pi_acceptor5).
gt(pi_acceptor7,pi_acceptor5).
gt(pi_acceptor8,pi_acceptor5).
gt(pi_acceptor9,pi_acceptor5).
gt(pi_acceptor7,pi_acceptor6).
gt(pi_acceptor8,pi_acceptor6).
gt(pi_acceptor9,pi_acceptor6).
gt(pi_acceptor8,pi_acceptor7).
gt(pi_acceptor9,pi_acceptor7).
gt(pi_acceptor9,pi_acceptor8).

gt(sigma1,sigma0).
gt(sigma2,sigma0).
gt(sigma3,sigma0).
gt(sigma4,sigma0).
gt(sigma5,sigma0).
gt(sigma6,sigma0).
gt(sigma7,sigma0).
gt(sigma8,sigma0).
gt(sigma9,sigma0).
gt(sigma2,sigma1).
gt(sigma3,sigma1).
gt(sigma4,sigma1).
gt(sigma5,sigma1).
gt(sigma6,sigma1).
gt(sigma7,sigma1).
gt(sigma8,sigma1).
gt(sigma9,sigma1).
gt(sigma3,sigma2).
gt(sigma4,sigma2).
gt(sigma5,sigma2).
gt(sigma6,sigma2).
gt(sigma7,sigma2).
gt(sigma8,sigma2).
gt(sigma9,sigma2).
gt(sigma4,sigma3).
gt(sigma5,sigma3).
gt(sigma6,sigma3).
gt(sigma7,sigma3).
gt(sigma8,sigma3).
gt(sigma9,sigma3).
gt(sigma5,sigma4).
gt(sigma6,sigma4).
gt(sigma7,sigma4).
gt(sigma8,sigma4).
gt(sigma9,sigma4).
gt(sigma6,sigma5).
gt(sigma7,sigma5).
gt(sigma8,sigma5).
gt(sigma9,sigma5).
gt(sigma7,sigma6).
gt(sigma8,sigma6).
gt(sigma9,sigma6).
gt(sigma8,sigma7).
gt(sigma9,sigma7).
gt(sigma9,sigma8).

gt(branch1,branch0).
gt(branch2,branch0).
gt(branch3,branch0).
gt(branch4,branch0).
gt(branch5,branch0).
gt(branch6,branch0).
gt(branch7,branch0).
gt(branch8,branch0).
gt(branch9,branch0).
gt(branch2,branch1).
gt(branch3,branch1).
gt(branch4,branch1).
gt(branch5,branch1).
gt(branch6,branch1).
gt(branch7,branch1).
gt(branch8,branch1).
gt(branch9,branch1).
gt(branch3,branch2).
gt(branch4,branch2).
gt(branch5,branch2).
gt(branch6,branch2).
gt(branch7,branch2).
gt(branch8,branch2).
gt(branch9,branch2).
gt(branch4,branch3).
gt(branch5,branch3).
gt(branch6,branch3).
gt(branch7,branch3).
gt(branch8,branch3).
gt(branch9,branch3).
gt(branch5,branch4).
gt(branch6,branch4).
gt(branch7,branch4).
gt(branch8,branch4).
gt(branch9,branch4).
gt(branch6,branch5).
gt(branch7,branch5).
gt(branch8,branch5).
gt(branch9,branch5).
gt(branch7,branch6).
gt(branch8,branch6).
gt(branch9,branch6).
gt(branch8,branch7).
gt(branch9,branch7).
gt(branch9,branch8).


gt(polarsiable1,polarsiable0).
gt(polarsiable2,polarsiable0).
gt(polarsiable3,polarsiable0).
gt(polarsiable4,polarsiable0).
gt(polarsiable5,polarsiable0).
gt(polarsiable6,polarsiable0).
gt(polarsiable7,polarsiable0).
gt(polarsiable8,polarsiable0).
gt(polarsiable9,polarsiable0).
gt(polarsiable2,polarsiable1).
gt(polarsiable3,polarsiable1).
gt(polarsiable4,polarsiable1).
gt(polarsiable5,polarsiable1).
gt(polarsiable6,polarsiable1).
gt(polarsiable7,polarsiable1).
gt(polarsiable8,polarsiable1).
gt(polarsiable9,polarsiable1).
gt(polarsiable3,polarsiable2).
gt(polarsiable4,polarsiable2).
gt(polarsiable5,polarsiable2).
gt(polarsiable6,polarsiable2).
gt(polarsiable7,polarsiable2).
gt(polarsiable8,polarsiable2).
gt(polarsiable9,polarsiable2).
gt(polarsiable4,polarsiable3).
gt(polarsiable5,polarsiable3).
gt(polarsiable6,polarsiable3).
gt(polarsiable7,polarsiable3).
gt(polarsiable8,polarsiable3).
gt(polarsiable9,polarsiable3).
gt(polarsiable5,polarsiable4).
gt(polarsiable6,polarsiable4).
gt(polarsiable7,polarsiable4).
gt(polarsiable8,polarsiable4).
gt(polarsiable9,polarsiable4).
gt(polarsiable6,polarsiable5).
gt(polarsiable7,polarsiable5).
gt(polarsiable8,polarsiable5).
gt(polarsiable9,polarsiable5).
gt(polarsiable7,polarsiable6).
gt(polarsiable8,polarsiable6).
gt(polarsiable9,polarsiable6).
gt(polarsiable8,polarsiable7).
gt(polarsiable9,polarsiable7).
gt(polarsiable9,polarsiable8).
